drop table items;
drop table orders;
drop table coupons;
drop table ordered_items;
drop table addresses;
drop table guest_customers;
drop table registered_customers;
drop table customers;
drop view full_customers;
